name: CI

on:
  pull_request:
    branches:
      - main  # Change this to your default branch name if different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies
        run: |
          npm install  # or yarn install if you prefer yarn

      - name: Run tests
        run: |
          npm run test  # or yarn test if you prefer yarn
